function generateRandomMessage() {
  const emojis = [
    "👽",
    "🐉",
    "🦄",
    "🔥",
    "💎",
    "🌀",
    "🌈",
    "🍄",
    "🦠",
    "🦖",
    "🦕",
    "🌌",
    "🍭",
    "🍬",
    "🍩",
    "💡",
    "🎠",
    "🛸",
    "🚀",
    "🎃",
    "🤖",
    "🔮",
    "🦑",
    "🦀",
    "🌪",
    "🌙",
    "⭐",
    "🌠",
    "💣",
    "🎉",
    "🍕",
    "🍔",
    "🍟",
    "🍺",
    "🍣",
    "🎲",
    "🧩",
    "🎮",
    "🎨",
    "🎭",
    "🎷",
    "🎸",
    "🎻",
    "🔊",
    "🎧",
    "🧙‍♂️",
    "🧚‍♀️",
    "🧜‍♂️",
    "🧞‍♀️",
    "🧟‍♂️",
  ];

  const characters =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

  const getRandomElement = (arr) => {
    const index = Math.floor(Math.random() * arr.length);
    return arr[index];
  };

  const getRandomString = (length) => {
    let result = "";
    for (let i = 0; i < length; i++) {
      result += getRandomElement(characters);
    }
    return result;
  };

  const randomLength = Math.floor(Math.random() * 20);
  const randomString = getRandomString(randomLength);
  const emoji = getRandomElement(emojis);
  return `${randomString} ${emoji}`;
}

function generateRandomUser() {
  const usernames = [
    "Luffgirl",
    "Cute_Sugarr",
    "Sweet_Sparrow",
    "The Inner Thing",
    "Etiolate",
    "Luciform",
    "Pie_Sweetness",
    "Oodles",
    "Bloom Kitty",
    "Nickbrinashipper",
    "Apropos",
    "Love_Insta",
    "Autumn Soul",
    "Moon_Up",
    "Cute Energy",
    "Corner To Corner",
    "Moongirl",
    "Smother Queen",
    "Jasmine",
    "Doll Stall",
    "Emaciate",
    "Teen_Rose",
    "Top_Command",
    "Glue Stu",
    "Fcstomper",
    "Chiaroscuro",
    "Geez God",
    "Locomate",
    "Speckled Dudess",
    "Genialkeebz",
    "Lovestump",
    "Hyper Zoom",
    "Doggondivis",
    "Funambulist",
    "Dream Girl",
    "Evil Weevil",
    "Bold_Style",
    "Bold_Touch",
    "Thought Motel",
    "Piggy_Honeybear",
    "Cyber Floss Lord",
    "Awesome_Girls",
    "Glam Angel",
    "Zombie Guide",
    "Muffinhead",
    "Pixel Anatomy",
    "Honey_Bell",
    "Purrienne_",
    "Sweet_Quail",
    "Summer Rain",
    "Caramel Cookie",
    "Whokissgirl",
    "Solacegirl",
    "Vergiform",
    "Bag Of Swag",
    "Cheeseinabag",
    "Mind Light",
    "Hug Me Tight",
    "Dragon Pie",
    "Olive Over Everything",
    "Rotten Disco Balls",
    "Wonky Buzz",
    "Apogee Point",
    "Yeah_Me",
    "Partycrasher",
    "Lemon Cupcake",
    "The Family Knot",
    "Panic_Point",
    "Sugar Momma",
    "Yautiagirl",
    "Angel_Doll",
    "Cislunar Doll",
    "Fluffycookie",
    "Shine Tin Molecules",
    "The Laidback Squirrel",
    "Goinggirl",
    "Sugar Free Diva",
    "Awkward Pink Stance",
    "Gold Unseen",
    "Posiripple",
    "Trendyschoolgirl",
    "Heyyounotyouyou",
    "Basket Of Dreams",
    "Happy In My Hut",
    "New Pole Meteorite",
    "Coriolis Extreme",
    "Divellent",
    "Respected",
    "Mostloved_Name",
    "Peafowl",
    "Starry Divinity",
    "Blue Thrill Bonzo",
    "Brain Drain Babe",
    "Doggie",
    "Awesome_Chocolate",
    "Pizza Topping Girl",
    "Top_To_Follow",
    "Cookie Angel",
    "Amazesgo0507",
    "Fly Like A Rat",
    "Droolbug",
    "Rainbow_Colours",
    "Lovely_Lights",
    "Shadow_Of_Love",
    "Hellohell",
    "Little Gorilla",
    "Meat_Duck",
    "Youarealienated",
    "Peppermint_Kisses",
    "Mocha Ooze",
    "Laurelwas",
    "Dolly_Dolphin",
    "Lyk Demon",
    "Brain Storm Angel",
    "Operaoflife",
    "Girlgaze",
    "Unforgiving Spleen",
    "Imported Sense",
    "Cute_Sugar",
    "Greed Hound",
    "Paralogism",
    "Firewalk Prophesy",
    "Torrentine",
    "Fantastic Fun",
    "Star_Belt",
    "Twinklinglights",
    "Singlemuffin",
    "Clown4u",
    "Dream Cloud Fiesta",
    "Smile_Somewhat",
    "Angelic Quest",
    "Coolchipz",
    "Butterscotch Seven",
    "Spoolgirl",
    "Egoflash",
    "Igczarevna",
    "Lovely_Dear",
    "Honey_Pot",
    "Glue Heart",
    "Angelberri",
    "Sleepy_World",
    "Bloom Thing",
  ];
  const getRandomElement = (arr) => {
    const index = Math.floor(Math.random() * arr.length);
    return arr[index];
  };
  let user = getRandomElement(usernames);
  return user;
}

function getRandomColor() {
    const colors = [
        "#FF6633",
        "#FFB399",
        "#FF33FF",
        "#FFFF99",
        "#00B3E6",
        "#E6B333",
        "#3366E6",
        "#999966",
        "#99FF99",
        "#B34D4D",
        "#80B300",
        "#809900",
        "#E6B3B3",
        "#6680B3",
        "#66991A",
        "#FF99E6",
        "#CCFF1A",
        "#FF1A66",
        "#E6331A",
        "#33FFCC",
        "#66994D",
        "#B366CC",
        "#4D8000",
        "#B33300",
        "#CC80CC",
        "#66664D",
        "#991AFF",
        "#E666FF",
        "#4DB3FF",
        "#1AB399",
        "#E666B3",
        "#33991A",
        "#CC9999",
        "#B3B31A",
        "#00E680",
        "#4D8066",
        "#809980",
        "#E6FF80",
        "#1AFF33",
        "#999933",
        "#FF3380",
        "#CCCC00",
        "#66E64D",
        "#4D80CC",
        "#9900B3",
        "#E64D66",
        "#4DB380",
        "#FF4D4D",
        "#99E6E6",
        "#6666FF",
    ];
    const getRandomElement = (arr) => {
        const index = Math.floor(Math.random() * arr.length);
        return arr[index];
    };
    let color = getRandomElement(colors);
    return color;
}

export { generateRandomMessage, generateRandomUser, getRandomColor };
